### ISSUE TITLE
Update README - Known Issues

### ISSUE THREAD

**Issue by sreichel** [inviqa/phpstan-magento1#3]
Instead of ignoring data/setup scripts, you can also supress this errors ....

```
includes:
    - vendor/inviqa/phpstan-magento1/extension.neon
parameters:
    reportUnmatchedIgnoredErrors: false
    autoload_files:
        - %currentWorkingDirectory%/app/Mage.php
    ignoreErrors:
        -
            message: '#Undefined variable: \$this#'
            paths:
                - %currentWorkingDirectory%/app/code/*/*/*/data/*
                - %currentWorkingDirectory%/app/code/*/*/*/sql/*
        -
            message: '#Using \$this outside a class.#'
            paths:
                - %currentWorkingDirectory%/app/code/*/*/*/data/*
                - %currentWorkingDirectory%/app/code/*/*/*/sql/*

```

Maybe you want to update the README.
